FROM node:10.23.3-alpine

RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
RUN apk --no-cache add --virtual builds-deps build-base python
ENV NODE_ENV test
RUN npm install
ENTRYPOINT ["npm", "run", "test"]